### PR TITLE
Libize (transform siplasplas libraries into library targets instead of header-only monstrosity)

### PR DESCRIPTION
**Pull request by Manu343726**

### CODE REVIEW

**Comment by vblanco20-1** [comment]
You sure you want to make them libraries, wich is normally harder to get into a project (have to link and control separate build) instead of just including the header you need?

**Comment by Manu343726** [comment]
It's not harder if you play nice with the build system, and that's what I'm trying to show with this. When this will be done, library distribution is as easy as running the MSI installer that cmake will generate.
Also library isolation helps with build times, debugging, testing, etc.

See how we integrate boost into the coroutine example, that's the kind of automatic distribution I'm trying to teach with cmake. gmock.cmake is another good example of this.

**Comment by Manu343726** [comment]
I will libize the reflection one when we finish with that topic in class. It's easier for me to scroll in one buffer only instead of switching between .cpp/.hpp files.

**Comment by Manu343726** [comment]
Opps

**Pull request merged**
